LilycoveCity_DepartmentStore_1F_Text_18BFB5:: @ 818BFB5
	.string "Ｗｅｌｃｏｍｅ ｔｏ \l"
	.string "ＤＥＰＡＲＴＭＥＮＴ ＳＴＯＲＥ．$"

LilycoveCity_DepartmentStore_1F_Text_18BFDB:: @ 818BFDB
	.string "Ｉｔ’ｓ ｓｏ ａｗｋｗａｒｄ ｔｏ\n"
	.string "ｂｕｙ ａｎｙｔｈｉｎｇ！ Ｗｈｙ\l"
	.string "ｅｖｅｎ ｈａｖｅ ｔｈｅ ｃｏｕｎｔｅｒ⸮$"

LilycoveCity_DepartmentStore_1F_Text_18C044:: @ 818C044
	.string "Ｄｉｄｎ’ｔ ｔｈｉｓ ｕｓｅｄ ｔｏ ｂｅ\n"
	.string "ＦＲＩＥＮＤＬＹ ＳＨＯＰ⸮$"

LilycoveCity_DepartmentStore_1F_Text_18C07A:: @ 818C07A
	.string "Ｉ ｆｏｕｎｄ ｔｈｉｓ ｂｌｕｅ\n"
	.string " ｔｈｉｎｇ ｉｎ ａ ｌａｋｅ！$"

LilycoveCity_DepartmentStore_1F_Text_18C0C3:: @ 818C0C3
	.string "AZUMARILL: Maririroo!$"

LilycoveCity_DepartmentStore_1F_Text_18C0D9:: @ 818C0D9
	.string "1F: ＳＥＲＶＩＣＥ\p"
	.string "2F: ＦＯＯＤ ＣＯＵＲＴ\p"
	.string "3F: ＰＨＡＲＭＡＣＹ\p"
	.string "4F: ＰＥＴ\p"
	.string "5F: ＳＰＯＲＴＳ ＧＯＯＤＳ\p"
	.string "ＲＯＯＦ: ＮＯＴＨＩＮＧ⸮⸮⸮$"
