LilycoveCity_DepartmentStore_5F_Text_18C4F9:: @ 818C4F9
	.string "Ｈｏｗ ｉｓ ｔｈｉｓ\n"
	.string "ＳＰＯＲＴＳ ＧＯＯＤＳ⸮ Ａｌｌ ｔｈｅｙ\l"
	.string "ｓｅｌｌ ａｒｅ ＢＩＫＥｓ！$"

LilycoveCity_DepartmentStore_5F_Text_18C556:: @ 818C556
	.string "Ｉ’ｍ ｇｏｎｎａ ｐｌａｙ ＢＡＳＥＢＡＬＬ\n"
	.string "ｗｉｔｈ ａ ＢＩＫＥ！$"

LilycoveCity_DepartmentStore_5F_Text_18C59F:: @ 818C59F
	.string "Ｉ’ｖｅ ｈｅａｒｄ ｔｈｅｓｅ ａｒｅ\p"
	.string "ｅｘｐｅｎｓｉｖｅ ｉｎ ｔｈｉｓ ｗｏｒｌｄ．．．\n"
	.string "Ｉｓ ｔｈａｔ ｔｒｕｅ⸮$"

UnknownString_818C5FA: @ 818C5FA
	.string "ＷＥ ＨＡＶＥ ＢＩＫＥＳ！\n"
	.string "5F: ＳＰＯＲＴＳ ＧＯＯＤＳ$"
