RustboroCity_Gym_Text_183A4B:: @ 8183A4B
	.string "Yo, how’s it going?\p"
	.string "Listen, my friend!\n"
	.string "Would you like to become the CHAMPION?\p"
	.string "I’m no TRAINER, not me, but I can\n"
	.string "sure give you winning advice.\p"
	.string "That’s settled, then! We’ll aim for the\n"
	.string "POKéMON CHAMPIONSHIP together!\p"
	.string "It’s your job as a TRAINER to collect\n"
	.string "GYM BADGES, am I right?\p"
	.string "But GYM LEADERS aren’t pushovers!\p"
	.string "And that’s where I come in!\n"
	.string "I’m here to provide expert advice!\p"
	.string "ROXANNE, the GYM LEADER, is a user\n"
	.string "of ROCK-type POKéMON.\p"
	.string "The ROCK type is very durable, but\n"
	.string "it can’t stand WATER-type and\l"
	.string "GRASS-type moves.\p"
	.string "Come see me afterwards, if you beat\n"
	.string "the GYM LEADER.\p"
	.string "Well, go for it!$"

RustboroCity_Gym_Text_183C90:: @ 8183C90
	.string "Whoa! What a breathtaking victory!\n"
	.string "My cheering must’ve worked!\p"
	.string "Great!\n"
	.string "Check your TRAINER CARD.\p"
	.string "The STONE BADGE you got should be\n"
	.string "properly recorded on it.\p"
	.string "In other words...\p"
	.string "You’ve climbed the first step on\n"
	.string "the stairs to the CHAMPIONSHIP!\p"
	.string "That’s got to feel awesome!$"

RustboroCity_Gym_Text_183D99:: @ 8183D99
	.string "Ｇｅｔ ｏｕｔｔａ ｈｅｒｅ, ｐｕｎｋ！\n"
	.string "Ｉ’ｌｌ ｐｒｏｔｅｃｔ ｔｈｅ ｌｅａｄｅｒ！$"

RustboroCity_Gym_Text_183DDD:: @ 8183DDD
	.string "Ｙｏｕ ｗｅｒｅ ｔｏｏ ｇｏｏｄ ｆｏｒ ｍｅ...$"

RustboroCity_Gym_Text_183DF9:: @ 8183DF9
	.string "Ｏｕｒ ｌｅａｄｅｒ ｉｓ ｗａｙ ｓｃａｒｉｅｒ\n"
	.string "ｔｈａｎ Ｉ ａｍ！$"

RustboroCity_Gym_Text_183E38:: @ 8183E38
	.string "Ｉｆ ｙｏｕ ｃａｎ’ｔ ｂｅａｔ ｍｅ,\n"
	.string "ｙｏｕ ｗｏｎ’ｔ ｓｔａｎｄ\l"
	.string "ａ ｃｈａｎｃｅ ａｇａｉｎｓｔ ＨＩＭ！$"

RustboroCity_Gym_Text_183E78:: @ 8183E78
	.string "Ｗｏｗ! Ｙｏｕ’ｖｅ ｇｏｔ ｓｏｍｅ ｐｏｔｅｎｔｉａｌ！$"

RustboroCity_Gym_Text_183E98:: @ 8183E98
	.string "ＨＥ ｉｓ ｓｔｒｏｎｇｅｒ ｔｈａｎ ｍｅ ｂｙ\n"
	.string "ｓｅｖｅｒａｌ ｔｉｍｅｓ．\p"
	.string "Ｙｏｕ’ｄ ｂｅｔｔｅｒ ｂｅ ｏｎ ｙｏｕｒ ｇｕａｒｄ！$"

RustboroCity_Gym_Text_183EE5:: @ 8183EE5
	.string "ⓈⓊⓅ Ⓚûóⓠ\n" 
	.string "ûⓉ’Ⓢ Ⓜô.\p" 
	.string "óûîⓅôⓇ ⓈîⓃⓈ ⓊⓃóôⓇⓉîⓁô.\p" 
	.string "ⓎíⓊ ⓀⓃíⓌ, ûⓉ’Ⓢ î ïôîⓊⓉûœⓊⓁ\n" 
	.string "óîⓎ íⓊⓉⓈûóô. ïûⓇóⓈ îⓇô\l" 
	.string "ⓈûⓃùûⓃù, œⓁíⓌôⓇⓈ îⓇô\n" 
	.string "ïⓁííⓂûⓃù. íⓃ óîⓎⓈ ⓁûⓀô\l" 
	.string "ⓉúôⓈô, ⓀûóⓈ ⓁûⓀô ⓎíⓊ...\p" 
	.string ". . .\p"
	.string "🇸🇭🇴🇺🇱🇩 🇧🇪 🇧🇺🇷🇳🇮🇳🇬 🇮🇳 🇭🇪🇱🇱.$" 

RustboroCity_Gym_Text_183FC4:: @ 8183FC4
	.string "ⓌôⓁⓅ.\n"
	.string "û ⓁíⓈⓉ...\p"
	.string "òíⓃùⓇîⓉⓈ, Ⓚûó.\n"
	.string "ⓈíⓇⓇⓎ œíⓇ Ⓣúô ïîûⓉ îⓃó ⓈⓌûⓉòú...\p"
	.string "ûⓉ ⓌîⓈ ⓈôòⓇôⓉⓁⓎ ⓂôⓂô ⓉⓇîⓈú\l"
	.string "Ⓣúô ôⓃⓉûⓇô ⓉûⓂô!\p"
	.string "ⓉúîⓃⓀⓈ œíⓇ îòⓉⓊîⓁⓁⓎ ⓅⓁîⓎûⓃù.\p"
	.string "íú, úôⓇôⓈ ⓎíⓊⓇ ïîóùô.\p"

RustboroCity_Gym_Text_1840AB:: @ 81840AB
	.string "{PLAYER} received the DIAPER\n"
	.string "from SANS UNDERTALE.$"

RustboroCity_Gym_Text_1840D5:: @ 81840D5
	.string "Ⓣúô ïîóùô ûⓈ ûⓃ \n"
	.string "Ⓣúô óûîⓅôⓇ.\p"
	.string "ⓉúûⓈ ñíⓀô ûⓈ ïîó îⓃó û\n"
	.string "ⓇôùⓇôⓉ óíûⓃù ûⓉ ïôœíⓇô û ôⓋôⓃ.\p"
	.string "œûⓃûⓈú ⓉⓎⓅûⓃù ⓉúûⓈ.$"

RustboroCity_Gym_Text_184170:: @ 8184170
	.string "úôⓇôⓈ î ⓉⓂ œíⓇ ⓁûⓀô\p"
	.string "ⓈíⓂô ⓇíòⓀ ⓂíⓋô û ⓉúûⓃⓀ$"

RustboroCity_Gym_Text_184252:: @ 8184252
	.string "ⓎíⓊ òîⓃ ñⓊⓈⓉ\n"
	.string "ⓆⓊûⓉ ⓅⓁîⓎûⓃù ⓃíⓌ $"

RustboroCity_Gym_Text_1842CC:: @ 81842CC
	.string "NEW PODUNK POKéMON GYM$"

RustboroCity_Gym_Text_1842E6:: @ 81842E6
	.string "NEW PODUNK POKéMON GYM\p"
	.string "SANESS’S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
