gBirchSpeech_Welcome:: @ 81C6D78
	.string "Ch-Champion! There you are!\n"
	.string "We’ve been looking all over\p"
	.string "for you! It’s me,\n"
	.string "PROFESSOR BIRCH!\p"
	.string "Remember me?\p$"

gBirchSpeech_ThisIsPokemon:: @ 81C6DF8
	.string "...You don’t? ...How about this?$"

gBirchSpeech_WorldInhabitedByPokemon:: @ 81C6E1A
	.string "Right, I know you remember what\n"
	.string "POKéMON are. Where were you,\l"
	.string "anyway? You’ve been missing\n"
	.string "for fourteen years!\p"
	.string "...............\p"
	.string "Wait, seriously? You’ve\n"
	.string "just been riding your bike\l"
	.string "past that weird leaf this\n"
	.string "entire time chasing the EON\l"
	.string "POKéMON, and battling a\n"
	.string "DUSKULL? ...Well, I hope\l"
	.string "it was rewarding......\p"
	.string "Anyway, that’s not why I’m\n"
	.string "here! Something big happened!\l"
	.string "I’ll explain after we reissue\n"
	.string "your TRAINER CARD.\p"

gBirchSpeech_AndYouAre:: @ 81C6FCB
	.string "Alright, first off...$"

gBirchSpeech_AreYouBoyOrGirl:: @ 81C6FD8
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gBirchSpeech_WhatsYourName:: @ 81C6FFA
	.string "All right.\n"
	.string "What’s your name?$"

gBirchSpeech_SoItsPlayer:: @ 81C7017
	.string "So it’s {PLAYER}{KUN}?$"

gBirchSpeech_AhOkayYouArePlayer:: @ 81C7025
	.string "Ah, right!\p"
	.string "You’re {PLAYER}{KUN} who became\n"
	.string "CHAMPION back in 2004!\l"
	.string "Boy, what a match that was!$"

gBirchSpeech_AreYouReady:: @ 81C7074
	.string "A-anyway! Apparently, there’s\n"
	.string "something called an “Ultra Wormhole”\l"
	.string "PROF. KUKUI called me to try to\n"
	.string "explain it but I didn’t really get it\p"
	.string "Anyway, some strange invaders from \n"
	.string "another dimension came through one,\l"
	.string "crashed their ship near LITTLE-\n"
	.string "ROOT, and started taking over\l"
	.string "everything, reshaping the region\n"
	.string "to look like their own home planet!\p"
	.string "Can you please go check it out and\l"
	.string "convince them to return home?\p"
	.string "We’ve all been run off, so we’re\n"
	.string "taking refuge in SOOTOPOLIS for the\l"
	.string "time being. They can’t get to us yet\n"
	.string "since they don’t have the HMs...\l"
	.string "I hear their ships coming though,\l"
	.string "so please hurry...!$"
