PetalburgCity_Text_16D361:: @ 816D361
	.string "WALLY: {PLAYER}...\n"
	.string "POKéMON hide in tall grass like this,\l"
	.string "don’t they?\p"
	.string "Please watch me and see if I can\n"
	.string "catch one properly.\p"
	.string "...Whoa!$"

PetalburgCity_Text_16D3DE:: @ 816D3DE
	.string "WALLY: I did it... It’s my...\n"
	.string "My POKéMON!$"

PetalburgCity_Text_16D408:: @ 816D408
	.string "{PLAYER}, thank you!\n"
	.string "Let’s go back to the GYM!$"

Route102_Text_16D431:: @ 816D431
	.string "Ｔｈｉｓ ｗｏｒｌｄ ｉｓ ｓｏ ｗｅｉｒｄ.\n"
	.string "Ｗｈａｔ ｅｖｅｎ ｉｓ ａ ＰＯＫＥＭＯＮ⸮$"

UnknownString_816D4A5: @ 816D4A5
	.string "Ｈｅｌｌｏ ｔｈｅｒｅ!$"

UnknownString_816D4BB: @ 816D4BB
	.string "ＮＥＷ ＰＯＤＵＮＫ ｉｓ ｔｏ ｔｈｅ ＥＡＳＴ.$"

Route102_Text_16D51A:: @ 816D51A
	.string "Ｉ’ｍ ｇｏｉｎｇ ｔｏ ｃａｔｃｈ ａ ｗｈｏｌｅ ｂｕｎｃｈ ｏｆ\n"
	.string "ＰＯＫＥＭＯＮ!$"

Route102_Text_16D547:: @ 816D547
	.string "ROUTE 102\n"
	.string "{0x7C} OLDALE TOWN$"

Route102_Text_16D55F:: @ 816D55F
	.string "ROUTE 102\n"
	.string "{0x7B} PETALBURG CITY$"
