LilycoveCity_DepartmentStore_3F_Text_18C24B:: @ 818C24B
	.string "Ａｒｅｎ’ｔ ｔｈｅｓｅ ｂａｓｉｃａｌｌｙ \n"
	.string "ｓｔｅｒｏｉｄｓ⸮ ＨＯＷ\l"
	.string "ＩＳ ＴＨＩＳ ＬＥＧＡＬ⸮⸮⸮$"

LilycoveCity_DepartmentStore_3F_Text_18C2B5:: @ 818C2B5
	.string "Ｉ ｗｏｎｄｅｒ ｗｈｙ \n"
	.string "ＰＯＴＩＯＮｓ ａｒｅ ｉｎ\l"
	.string "ｔｈｅ ＦＯＯＤ ＣＯＵＲＴ⸮\n"
	.string "ＴＨＥＹ ＴＡＳＴＥ ＢＡＤ！！！$"

LilycoveCity_DepartmentStore_3F_Text_18C32E:: @ 818C32E
	.string "Ｍｙ ＰＯＫＥＭＯＮ ｏｖｅｒｄｏｓｅｄ\n"
	.string "ｏｎ ＣＡＲＢＯＳ！$"

UnknownString_818C363: @ 818C363
	.string "ＰＩＬＬＳ ＨＥＲＥ！\n"
	.string "3F: ＰＨＡＲＭＡＣＹ$"
