ClosedSootopolisDoorText: @ 8169690
	.string "The door is closed.$"

SootopolisCity_Text_1696A4:: @ 81696A4
	.string "Ｗｈｏ ｍｉｇｈｔ ｙｏｕ ｂｅ⸮\p"
	.string "Ｔｈｉｓ ｉｓ ＮＥＷ ＰＯＤＵＮＫ.\p"
	.string "Ｏｎｌｙ ＣＯＯＬ ＫＩＤＳ ａｒｅ\n"
	.string "ａｌｌｏｗｅｄ ｈｅｒｅ.\p"
	.string "Ｐｌｅａｓｅ ｌｅａｖｅ.$"

SootopolisCity_Text_16972B:: @ 816972B
	.string "Ｄｏｎ’ｔ ｇｏ ｉｎ ｔｈｅ\n"
	.string "ＣＲＹＰＴ ｉｎ ｔｈｅ ＧＲＡＶＥＹＡＲＤ!\p"
	.string "Ｏｕｒ ｌｅａｄｅｒ ｉｓ ｔｈｅｒｅ!$"

SootopolisCity_Text_1697A7:: @ 81697A7
	.string "Ｉ... Ｉ’ｖｅ ｎｅｖｅｒ ｂｅｅｎ ｏｕｔ ｏｆ ｔｈｉｓ ｃｉｔｙ.\p"
	.string "Ｉｓ ｉｔ ｔｒｕｅ ｏｔｈｅｒ ｔｏｗｎｓ\n"
	.string "ａｒｅｎ’ｔ ａｓ ｓｌａｎｔｅｄ⸮$"

SootopolisCity_Text_169813:: @ 8169813
	.string "Ｈｍ!\n"
	.string "Ｔｈｉｓ ｒｏｍｈａｃｋ ｓｔｉｎｋｓ!$"

SootopolisCity_Text_1698A0:: @ 81698A0
	.string "ＮＥＷ ＰＯＤＵＮＫ ｉｓ ｎａｍｅｄ\n"
	.string "ａｆｔｅｒ ｓｏｍｅ ｏｌｄ ｃｉｔｙ\p"
	.string "ｏｕｒ ｌｅａｄｅｒ ｕｓｅｄ ｔｏ\n"
	.string "ｌｉｖｅ ｉｎ, ａｐｐａｒｅｎｔｌｙ.$"

SootopolisCity_Text_169988:: @ 8169988
	.string "STEVEN: {PLAYER}{KUN}, you came, too?\n"
	.string "In this terrible rainstorm, yet...\p"
	.string "Oh, yes, can you hear out what my\n"
	.string "friend has to say?$"

SootopolisCity_Text_1699FD:: @ 81699FD
	.string "My name is WALLACE.\n"
	.string "I’m this town’s GYM LEADER.\p"
	.string "I’ve also been entrusted with the\n"
	.string "protection of the CAVE OF ORIGIN.\p"
	.string "This downpour is caused by a power\n"
	.string "emanating from the CAVE OF ORIGIN.$"

SootopolisCity_Text_169AB7:: @ 8169AB7
	.string "That... That is the BLUE ORB.\p"
	.string "I see.\n"
	.string "Follow me.$"

SootopolisCity_Text_169AE7:: @ 8169AE7
	.string "STEVEN: This rain...\p"
	.string "People and POKéMON need water to live...\p"
	.string "But why does this rain fill us with\n"
	.string "so much dread?\p"
	.string "The rain clouds over SOOTOPOLIS will\n"
	.string "keep building and soon extend all\l"
	.string "over HOENN...\p"
	.string "If that were to happen...$"

SootopolisCity_Text_169BC7:: @ 8169BC7
	.string "WALLACE: The CAVE OF ORIGIN is ahead.\p"
	.string "No one from SOOTOPOLIS is permitted\n"
	.string "to enter the CAVE OF ORIGIN.\p"
	.string "But you must go.\n"
	.string "Together with your BLUE ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_169C99:: @ 8169C99
	.string "STEVEN: {PLAYER}{KUN}, I never expected you\n"
	.string "to be holding the BLUE ORB.\p"
	.string "You’ll be okay. With your POKéMON,\n"
	.string "you’ll get things done no matter what.\p"
	.string "I’m convinced of it!$"

SootopolisCity_Text_169D37:: @ 8169D37
	.string "WALLACE: You must go together with\n"
	.string "your BLUE ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_169DA6:: @ 8169DA6
	.string "STEVEN: You’ll be okay. With your\n"
	.string "POKéMON, you’ll get things done\l"
	.string "whatever happens.\p"
	.string "I’m convinced of it!$"

SootopolisCity_Text_169E0F:: @ 8169E0F
	.string "STEVEN: {PLAYER}{KUN}, you came, too?\n"
	.string "Under this scorching sun, yet...\p"
	.string "Oh, yes, can you hear out what my\n"
	.string "friend has to say?$"

SootopolisCity_Text_169E82:: @ 8169E82
	.string "My name is WALLACE.\n"
	.string "I’m this town’s GYM LEADER.\p"
	.string "I’ve also been entrusted with the\n"
	.string "protection of the CAVE OF ORIGIN.\p"
	.string "This sunshine is caused by a power\n"
	.string "emanating from the CAVE OF ORIGIN.$"

SootopolisCity_Text_169F3C:: @ 8169F3C
	.string "That... That is the RED ORB.\p"
	.string "I see.\n"
	.string "Follow me.$"

SootopolisCity_Text_169F6B:: @ 8169F6B
	.string "STEVEN: This sunlight...\p"
	.string "People and POKéMON need sunlight\n"
	.string "to live...\p"
	.string "But why does this sunlight fill us\n"
	.string "with so much dread?\p"
	.string "The blazing sun over SOOTOPOLIS is\n"
	.string "intensifying... Soon, all of HOENN\l"
	.string "will be under its withering glare...\p"
	.string "If that were to happen...$"

SootopolisCity_Text_16A06C:: @ 816A06C
	.string "WALLACE: The CAVE OF ORIGIN is ahead.\p"
	.string "No one from SOOTOPOLIS is permitted\n"
	.string "to enter the CAVE OF ORIGIN.\p"
	.string "But you must go. \n"
	.string "Together with your RED ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_16A13E:: @ 816A13E
	.string "ＯＵＴＴＡ ＭＹ ＷＡＹ ＫＩＤ!$"

SootopolisCity_Text_16A1DB:: @ 816A1DB
	.string "WALLACE: You must go together with\n"
	.string "your RED ORB.\p"
	.string "You must go regardless of what awaits\n"
	.string "you inside the CAVE...$"

SootopolisCity_Text_16A249:: @ 816A249
	.string "ＯＨ ＮＯ Ｉ ＭＩＳＳＥＤ \n"
	.string "ＴＨＥ ＳＡＬＥ!$"

SootopolisCity_Text_16A2B2:: @ 816A2B2
	.string "The legend told by the old man on\n"
	.string "MT. PYRE... It wasn’t a made-up story.$"

SootopolisCity_Text_16A2FB:: @ 816A2FB
	.string "The natural balance of HOENN is going\n"
	.string "through a wrenching shift...$"

SootopolisCity_Text_16A33E:: @ 816A33E
	.string "STEVEN: {PLAYER}{KUN}, we owe it all to you.\p"
	.string "The sky above SOOTOPOLIS has returned\n"
	.string "to normal. For that, WALLACE sends his\l"
	.string "thanks, too.\p"
	.string "And, that same WALLACE is waiting for\n"
	.string "you inside.\p"
	.string "He’s strong.\n"
	.string "But the way you are now, you should be\l"
	.string "on equal footing with him.\p"
	.string "Give it your best shot.$"

SootopolisCity_Text_16A455:: @ 816A455
	.string "Ａｌｌ ｌｉｆｅ ｓｔａｒｔｓ ｗｉｔｈ ｂｏｎｅｓ,\n"
	.string "ａｎｄ ｉｔ ａｌｌ ｅｎｄｓ ｗｉｔｈ ｂｏｎｅｓ...\p"
	.string "Ｗｈｅｒｅ ｄｏ ｔｈｅ ｓｋｅｌｅｔｏｎｓ\n"
	.string "ｃｏｍｅ ｆｒｏｍ ａｎｙｗａｙ⸮⸮⸮$"

SootopolisCity_Text_16A4D6:: @ 816A4D6
	.string "Ｌｅｔ ｍｅ ｇｕｅｓｓ, ｙｏｕ’ｒｅ ｇｏｉｎｇ ｔｏ\n"
	.string "ｃｈａｌｌｅｎｇｅ ｏｕｒ ｌｅａｄｅｒ⸮\p"
	.string "Ｏｈ, ｙｏｕ ａｒｅ ｒｅａｌｌｙ⸮\n"
	.string "Ｙｏｕ’ｒｅ ａｗｆｕｌｌｙ ｂｒａｖｅ!$"

SootopolisCity_Text_16A531:: @ 816A531
	.string "Ｌｅｔ ｍｅ ｇｕｅｓｓ, ｙｏｕ’ｖｅ ｂｅａｔｅｎ ｈｉｍ!\n"
	.string "Ｏｈ, ｙｏｕ ｄｉｄ, ｒｅａｌｌｙ⸮\p"
	.string "Ｗｅｒｅ ｙｏｕ ｅｘｐｅｃｔｉｎｇ ｔｈａｔ⸮$"

SootopolisCity_Text_16A587:: @ 816A587
	.string "Ｈｍ!\n"
	.string "Ｔｈｉｓ ｒｏｍｈａｃｋ ｓｔｉｎｋｓ!$"

SootopolisCity_Text_16A614:: @ 816A614
	.string "Ｉ’ｍ ｇｌａｄ ｗｅ ｇｏｔ \n"
	.string "ｔｒａｎｓｐｏｒｔｅｄ ｈｅｒｅ...\p"
	.string "Ｔｈｅ ｇｒａｐｈｉｃｓ ｌｏｏｋ ｓｏ\n"
	.string "ｍｕｃｈ ｎｉｃｅｒ ｏｎ ＧＢＡ!$"

SootopolisCity_Text_16A6AE:: @ 816A6AE
	.string "Ｈｕｎｈ⸮ Ｗｈｅｒｅ ｉｓ ｍｙ ｈｏｕｓｅ ?$"

SootopolisCity_Text_16A6C7:: @ 816A6C7
	.string "NEW PODUNK CITY POKéMON GYM\n"
	.string "LEADER: SANESS\p"
	.string "“diaper sans undertale”$"

SootopolisCity_Text_16A711:: @ 816A711
	.string "Ｔｈｅ ｇｒａｖｅｙａｒｄ\n"
	.string "ａｎｄ “ｇｙｍ”\l"
	.string "ｉｓ ｊｕｓｔ ｕｐ ａｈｅａｄ!$"
