LilycoveCity_DepartmentStore_4F_EventObjects::
	object_event 1, EVENT_OBJ_GFX_GENTLEMAN, 0, 7, 6, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, LilycoveCity_DepartmentStore_4F_EventScript_159FFE, 0
	object_event 2, EVENT_OBJ_GFX_WOMAN_3, 0, 1, 6, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, LilycoveCity_DepartmentStore_4F_EventScript_15A007, 0
	object_event 3, EVENT_OBJ_GFX_YOUNGSTER, 0, 14, 5, 3, MOVEMENT_TYPE_WANDER_AROUND, 1, 1, 0, 0, LilycoveCity_DepartmentStore_4F_EventScript_15A010, 0
	object_event 4, EVENT_OBJ_GFX_WOMAN_4, 0, 8, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, LilycoveCity_DepartmentStore_4F_EventScript_15A019, 0
	object_event 5, EVENT_OBJ_GFX_WOMAN_4, 0, 10, 2, 3, MOVEMENT_TYPE_FACE_DOWN, 0, 0, 0, 0, LilycoveCity_DepartmentStore_4F_EventScript_15A03C, 0

LilycoveCity_DepartmentStore_4F_MapWarps::
	warp_def 1, 3, 0, 1, MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F
	warp_def 2, 2, 0, 0, MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F
	warp_def 4, 1, 0, 0, MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR

LilycoveCity_DepartmentStore_4F_MapEvents::
	map_events LilycoveCity_DepartmentStore_4F_EventObjects, LilycoveCity_DepartmentStore_4F_MapWarps, 0x0, 0x0
