LilycoveCity_DepartmentStore_4F_Text_18C39C:: @ 818C39C
	.string "Ｈｍｍ．．．\p"
	.string "Ｗｈｙ ｄｏ ｐｅｏｐｌｅ ｅｖｅｒ\n"
	.string "ｕｓｅ ｄｅｆｅｎｓｉｖｅ ｍｏｖｅｓ⸮$"

LilycoveCity_DepartmentStore_4F_Text_18C41B:: @ 818C41B
	.string "Ｉ ｔｈｏｕｇｈｔ ｔｈｉｓ ｗａｓ\n"
	.string "ａ ＰＥＴ ＳＴＯＲＥ．．．$"

LilycoveCity_DepartmentStore_4F_Text_18C481:: @ 818C481
	.string "Ｙｅａｈ Ｉ’ｄ ｌｉｋｅ ａ ｂｏｎｅｌｅｓｓ\n"
	.string "ＰＩＫＡＣＨＵ, ｐｌｅａｓｅ！$"

UnknownString_818C4CE: @ 818C4CE
	.string "ＳＨＯＷ ＭＥ ＹＯＵＲ ＭＯＶＥＳ\n"
	.string "4F: ＰＥＴ$"
