LilycoveCity_DepartmentStore_2F_Text_18C162:: @ 818C162
	.string "Ｉ ｓｕｒｅ ｄｏ ｅｎｊｏｙ ＢＵＲＧＳ！$"

LilycoveCity_DepartmentStore_2F_Text_18C195:: @ 818C195
	.string "Ｉ ｌｏｖｅ ＢＵＲＧＳ！\n"
	.string "Ｇｏｔｔａ ｈａｖｅ ｍｙ ＢＵＲＧＳ！$"

LilycoveCity_DepartmentStore_2F_Text_18C1D9:: @ 818C1D9
	.string "ＴＨＥ ＦＯＯＤ ＩＳ ＬＡＣＥＤ\n"
	.string "ＷＩＴＨ ＭＩＮＤ ＣＯＮＴＲＯＬ\n"
	.string "ＤＲＵＧＳ！\n"
	.string "ＴＨＥ ＧＯＶＥＲＮＭＥＮＴ\n"
	.string "ＩＳ ＢＥＨＩＮＤ ＴＨＩＳ！\n"
	.string "ＷＡＫＥ ＵＰ ＳＨＥＥＰＬＥ！$"

UnknownString_818C21A: @ 818C21A
	.string "ＹＵＭＭＹ！\n"
	.string "2F: ＦＯＯＤ ＣＯＵＲＴ$"
